services:
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db 
       
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    depends_on:
      - backend
    volumes:
      - '.:/app'
      - app/node_modules
      
  backend:
    build: ./backend-server
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/todoDB
    depends_on:
      - mongodb

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
