version: '3'
services:
  frontend:
    image: kbimsara/cloud-app-dev:frontend
    ports:
      - "3000:3000"

  backend1:
    image: kbimsara/cloud-app-dev:backend
    expose:
      - "4000"

  backend2:
    image: kbimsara/cloud-app-dev:backend
    expose:
      - "4000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
