version: '3'

services:
  frontend:
    image: kbimsara/dev-todo:frontend  # This will pull the image from Docker Hub
    ports:
      - "3000:3000"
    depends_on:
      - nginx  # Frontend depends on NGINX

  backend1:
    image: kbimsara/dev-todo:backend  # This will pull the image from Docker Hub
    expose:
      - "4000"  # Exposes the port internally to NGINX
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo  # MongoDB connection URL
    depends_on:
      - mongo

  backend2:
    image: kbimsara/dev-todo:backend  # This will pull the image from Docker Hub
    expose:
      - "4000"  # Exposes the port internally to NGINX
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo  # MongoDB connection URL
    depends_on:
      - mongo

  mongo:
    image: mongo:latest  # Tag for your custom MongoDB image
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: kbimsara/dev-todo:nginx  # This will pull the image from Docker Hub
    ports:
      - "80:80"  # NGINX load balancer listens on port 80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Correct path to nginx.conf
    depends_on:
      - backend1
      - backend2
      - mongo

volumes:
  mongo-data:
