version: '3.8'

services:
  frontend:
    image: $DOCKER_USERNAME/dev-todo:frontend
    container_name: frontend
    ports:
      - "3000:3000"

  backend1:
    image: $DOCKER_USERNAME/dev-todo:backend
    container_name: backend1
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo

  backend2:
    image: $DOCKER_USERNAME/dev-todo:backend
    container_name: backend2
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo

  mongo:
    image: $DOCKER_USERNAME/dev-todo:mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: $DOCKER_USERNAME/dev-todo:nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2

volumes:
  mongo_data:
