version: '3'

services:
  frontend:
    image: kbimsara/dev-todo:frontend  # This will pull the image from Docker Hub
    ports:
      - "3000:3000"

  backend1:
    image: kbimsara/dev-todo:backend  # This will pull the image from Docker Hub
    expose:
      - "4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo  # MongoDB connection URL

  backend2:
    image: kbimsara/dev-todo:backend  # This will pull the image from Docker Hub
    expose:
      - "4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo  # MongoDB connection URL

  nginx:
    image: kbimsara/dev-todo:nginx  # This will pull the image from Docker Hub
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - mongo

  mongo:
    image: dev-todo:mongo  # Tag for your custom MongoDB image
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
