services:
  mongodb:
    image: kbimsara/cloud-app-dev:mongo
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db 

  frontend:
    image: kbimsara/cloud-app-dev:frontend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    depends_on:
      - backend

  backend:
    image: kbimsara/cloud-app-dev:backend
    ports:
      - "5000:5000"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/todoDB
    depends_on:
      - mongodb

  
volumes:
  mongo-data:
