# Use the official MongoDB image as the base
FROM mongo:6.0

# Set the working directory
WORKDIR /data

# Expose the MongoDB default port
EXPOSE 27017

# Command to run MongoDB (default entrypoint already handles this)
CMD ["mongod"]
