name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: List Files in Root Directory
      run: ls -al

    - name: Navigate to ToDo Directory
      run: cd "Docker-Dev/ToDo" && ls -al

    - name: Build and Push Docker Images
      run: |
        cd "Docker-Dev/ToDo"
        docker-compose build
        docker-compose push
