name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Directory Structure
      run: ls -R

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: List Files in Repository
      run: ls -al

    - name: Build Front-end
      run: |
        cd "./ToDo/front-end" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-tod:frontend .

    - name: Build Back-end
      run: |
        cd "./ToDo/backend-server" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-tod:backend .

    - name: Build MongoDB
      run: |
        cd "./ToDo/mongoDB" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-tod:mongo .

    # - name: Build and Push Docker Images
    #   run: |
    #     cd "./ToDo"  
    #     docker-compose build
    #     docker-compose push

    - name: Print All Docker Images
      run: |
        docker images 
        
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:mongo
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:backend
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:frontend
