name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Directory Structure
      run: ls -R

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Front-end
      run: |
        cd "./ToDo/front-end" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-todo:frontend .

    - name: Build Back-end
      run: |
        cd "./ToDo/backend-server" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-todo:backend .

    # - name: Build MongoDB
    #   run: |
    #     cd "./ToDo/mongoDB" 
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-todo:mongo .

    - name: Build NGINX
      run: |
        cd "./ToDo/nginx" 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-todo:nginx .

    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:backend
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/dev-todo:nginx

    - name: Print All Docker Images
      run: docker images
